# .github/workflows/check.yml

name: Apollo

# Controls when the action will run. Triggers the workflow on push request events
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.26.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      # TBD: only run this command with the `--background` flag once we have the Apollo Studio GitHub integration enabled on your repository
      - name: Run destinations subgraph check
        run: |
          rover subgraph check O11Y-Workshop-0@current --schema ./subgraphs/destinations/schema.graphql --name destinations --background
      - name: Run experiences subgraph check
        run: |
          rover subgraph check O11Y-Workshop-0@current --schema ./subgraphs/experiences/schema.graphql --name experiences --background

  publish:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: apollo
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.sha }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.26.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Publish destinations subgraph
        run: |
          ./publish-destinations-current.sh
      - name: Publish experiences subgraph
        run: |
          ./publish-experiences-current.sh
